<a href="https://colab.research.google.com/github/AnujDawar/pieran_data-tensorflow2/blob/master/00-NumPy-Crash-Course/03-NumPy-Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

___

<a href='http://www.pieriandata.com'><img src='https://github.com/AnujDawar/pieran_data-tensorflow2/blob/master/00-NumPy-Crash-Course/Pierian_Data_Logo.png?raw=1'/></a>
___
<center><em>Copyright Pierian Data</em></center>
<center><em>For more information, visit us at <a href='http://www.pieriandata.com'>www.pieriandata.com</a></em></center>

# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.

<div class="alert alert-danger" style="margin: 10px"><strong>IMPORTANT NOTE!</strong> Make sure you don't run the cells directly above the example output shown, <br>otherwise you will end up writing over the example output!</div>

#### 1. Import NumPy as np

In [0]:
import numpy as np

#### 2. Create an array of 10 zeros 

In [5]:
# CODE HERE
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [0]:
# DON'T WRITE HERE

#### 3. Create an array of 10 ones

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [0]:
# DON'T WRITE HERE

#### 4. Create an array of 10 fives

In [9]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [0]:
# DON'T WRITE HERE

#### 5. Create an array of the integers from 10 to 50

In [11]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [0]:
# DON'T WRITE HERE

#### 6. Create an array of all the even integers from 10 to 50

In [13]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [0]:
# DON'T WRITE HERE

#### 7. Create a 3x3 matrix with values ranging from 0 to 8

In [15]:
np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [0]:
# DON'T WRITE HERE

#### 8. Create a 3x3 identity matrix

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [0]:
# DON'T WRITE HERE

#### 9. Use NumPy to generate a random number between 0 and 1<br><br>&emsp;NOTE: Your result's value should be different from the one shown below.

In [19]:
np.random.rand(1)

array([0.03591126])

In [0]:
# DON'T WRITE HERE

#### 10. Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution<br><br>&emsp;&ensp;NOTE: Your result's values should be different from the ones shown below.

In [21]:
np.random.randn(25)

array([ 0.38508558,  0.70081914, -1.19726171,  1.25457787, -0.67246919,
       -0.26320309, -0.94774797,  1.96008391,  0.29049848, -0.56355645,
        1.23002452,  0.62602413, -0.36016271, -1.91337694, -0.46689063,
        0.50816147, -0.51227244,  0.21127369,  1.23650438, -1.40320951,
        1.41215253, -0.8015365 ,  1.46627472,  0.21909938, -1.10348463])

In [0]:
# DON'T WRITE HERE

#### 11. Create the following matrix:

In [23]:
np.arange(0.01, 1.01, 0.01).reshape(10, 10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [0]:
# DON'T WRITE HERE

#### 12. Create an array of 20 linearly spaced points between 0 and 1:

In [25]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [0]:
# DON'T WRITE HERE

## Numpy Indexing and Selection

Now you will be given a starting matrix (be sure to run the cell below!), and be asked to replicate the resulting matrix outputs:

In [27]:
# RUN THIS CELL - THIS IS OUR STARTING MATRIX
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 13. Write code that reproduces the output shown below.<br><br>&emsp;&ensp;Be careful not to run the cell immediately above the output, otherwise you won't be able to see the output any more.

In [28]:
# CODE HERE
mat[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [0]:
# DON'T WRITE HERE

#### 14. Write code that reproduces the output shown below.

In [30]:
mat[3, 4]

20

In [0]:
# DON'T WRITE HERE

#### 15. Write code that reproduces the output shown below.

In [32]:
mat[:3, 1].reshape(3, 1)

array([[ 2],
       [ 7],
       [12]])

In [0]:
# DON'T WRITE HERE

#### 16. Write code that reproduces the output shown below.

In [35]:
mat[-1]

array([21, 22, 23, 24, 25])

In [0]:
# DON'T WRITE HERE

array([21, 22, 23, 24, 25])

#### 17. Write code that reproduces the output shown below.

In [37]:
mat[-2:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [0]:
# DON'T WRITE HERE

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## NumPy Operations

#### 18. Get the sum of all the values in mat

In [38]:
mat.sum()

325

In [0]:
# DON'T WRITE HERE

325

#### 19. Get the standard deviation of the values in mat

In [39]:
mat.std()

7.211102550927978

In [0]:
# DON'T WRITE HERE

7.211102550927978

#### 20. Get the sum of all the columns in mat

In [40]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [0]:
# DON'T WRITE HERE

array([55, 60, 65, 70, 75])

## Bonus Question
We worked a lot with random data with numpy, but is there a way we can insure that we always get the same random numbers? What does the seed value mean? Does it matter what the actual number is? [Click Here for a Hint](https://www.google.com/search?q=numpy+random+seed)

# Great Job!